### ISSUE TITLE
Would you consider adding perl support?

### ISSUE THREAD

**Issue by johnjelinek** [docker-library/nginx#1]
http://serverfault.com/a/247358/116303

This would allow me to capture my linked containers' IP addresses using something like `perl_set $ghost 'sub { return $ENV{"GHOST_PORT_2368_TCP_ADDR"}; }';`, which I can then use in `upstream`/`server` placement.

**Comment by yosifkit** [comment]
Perl support would be great.  Do you know if this would adversely affect the size of the image or complexity of the build?  Does upstream recommend enabling perl support by default?  We would definitely not be opposed to a pull request if this is the desire of nginx users.

**Comment by johnjelinek** [comment]
@yosifkit: Please see comments in #2. I don't know if upstream recommends enabling support by default, I know it's an optional component. I don't know of any security risks by having it enabled.

**Comment by tianon** [comment]
Sounds good to me - Perl is nice. :)
