### ISSUE TITLE
["nginx"] should be the ENTRYPOINT, not CMD

### ISSUE THREAD

**Issue by stuartpb** [docker-library/nginx#12]
I should be able to do `docker run nginx --whatever --commands` without having to specify `nginx` twice.

I'd even go so far as to say that the entrypoint should be `["nginx", "-g", "daemon off;"]`, but Nginx seems to choke if it finds a duplicate entry for `daemon off;` in the configuration.

**Comment by yosifkit** [comment]
We have been standardizing CMD for the default command for all official base images.  It is easier to override (`docker run -it  nginx bash` vs `docker run -it --entrypoint=/bin/bash nginx -i`).  It can throw off a user if they say `bash` and still get nginx running or just an error.  We have been using entrypoint for start scripts that need access to possibly mounted volumes (see [docker-library/postgres](http://github.com/docker-library/postgres)).  We are still working to fully document the styles and guidelines of Official Images.

**Comment by yankeeinlondon** [comment]
I thought it was accepted conventional wisdom to use ENTRYPOINT? In 99% of cases you'd want to just provide nginx switches as options to the **run** right? Using ENTRYPOINT you get:

``` bash
# show configuration options
sudo docker run nginx:1.x -v
# send signalling to nginx:1.x
sudo docker run nginx:1.x -s reload
```

This feels very natural an mimics the signature of a bare-metal implementation. In comparison, the CMD approach requires the awkward double nginx reference:

``` bash
# show configuration options
sudo docker run nginx:1.x nginx -v
# send signalling to nginx:1.x
sudo docker run nginx:1.x nginx -s reload
```

Furthermore, if the use cases you're looking to make easier are getting inside a running **container** then you'd still really need something like `nsenter`/`nsinit` wouldn't you? To get an interactive session with the nginx **image** then the `--entrypoint` example makes sense but this is I think less common and if people find themselves needing to do this with their images then creating a simple Bash shortcut like:

``` bash
function into () {
    if [[ -z "$1" ]]; then
        echo "Usage:"
        echo "   into [image-id]"
        echo ""
        echo "Current Images: [sudo docker images]"
        echo ""
        sudo docker images
    else
        echo "Jumping into Docker Image:"
        echo "  - sudo docker run -it --entrypoint=\"/bin/bash\" \"$1\""
        sudo docker run -it --entrypoint="/bin/bash" "$1"
    fi
}
```

Similarly I have done the same thing with jumping into running containers (which I find generally more useful):

``` bash
function container () {
    if [[ -z "$1" ]];then
        echo "You must supply the container-id (or name)"
    else
        PID=`sudo docker inspect --format "{{ .State.Pid }}" $1`
        echo "Process ID is "$PID
        sudo nsenter --target "$PID" --mount --uts --ipc --net --pid
    fi
}
```

**Comment by yosifkit** [comment]
So, in order to make it simpler for starting users, official images will not be using `entrypoint` instead of `cmd`. Refs: [best practices#cmd](https://docs.docker.com/articles/dockerfile_best-practices/#cmd), [best practices#entrypoint](https://docs.docker.com/articles/dockerfile_best-practices/#entrypoint).

Nginx upstream will now be providing and maintaining the images [nginxinc/docker-nginx](https://github.com/nginxinc/docker-nginx).

**Comment by anapsix** [comment]
moved my rant to docker-library/official-images#692
