### ISSUE TITLE
Remove this repo?

### ISSUE THREAD

**Issue by ahmetb** [docker-library/nginx#15]
Looks like this repo is not used anymore. I spent quite some time until I realized this is not the repo used to build `library/nginx` today. So maybe this repo should go away or have some deprecation notice?

**Comment by tianon** [comment]
![screenshot_2015-08-14-08-06-36](https://cloud.githubusercontent.com/assets/161631/9276887/797b6c10-425b-11e5-9511-d49fdd88e5f8.png)
You mean like the notice it already has? :wink: 

The best way to find the source code of any of the official images is to follow the Dockerfile links at the top of the image description.

**Comment by ahmetb** [comment]
My bad.

**Comment by tianon** [comment]
No worries! :smile: 

What could we do instead to make it more obvious without just deleting the repo outright? (since it does still have some useful issue/commit history in it)

**Comment by ahmetb** [comment]
Best thing I can think of is transferring repo to a personal account, if you want to keep it for souvenir purposes. But I guess no big deal, I was just wildly browsing official repos and my hands typed nginx into the address bar instead of going though Docker Hub.
