### ISSUE TITLE
nginx runs directly as root

### ISSUE THREAD

**Issue by AsavarTzeth** [docker-library/nginx#4]
I discovered a potential issue with the container. The server is started directly from the root user.

Is this an issue, or not? I know the process spawns a child running as www-data, so I may be way off. I just thought I would ask since docker really does not offer secure isolation at this time.

**Comment by tianon** [comment]
I think when we originally tried running it as `www-data` instead, it didn't work, and then we saw that it does spawn a child worker non-root, so we figured that was enough for a first iteration, but we'll dig in again and see what can be done here, because it should definitely be possible to run even the main daemon here without root.

**Comment by yosifkit** [comment]
I was redoing the nginx so that it would be smaller (down to 173MB) and found the reason we do not run as www-data.

``` console
$ docker run -it --rm -p=3333:80 nginx:1.7.4
nginx: [alert] could not open error log file: open() "/proc/self/fd/2" failed (13: Permission denied)
2014/08/22 23:54:12 [emerg] 1#0: open() "/proc/self/fd/1" failed (13: Permission denied)
```

Any ideas to fix this so we can run as www-data?

**Comment by tianon** [comment]
Is that through "gosu", or directly via USER / -u ?

**Comment by yosifkit** [comment]
Dockerfile with `USER www-data`.

**Comment by tianon** [comment]
Ack, we're getting bitten by https://github.com/docker/docker/issues/6880.  Shoot.

**Comment by AsavarTzeth** [comment]
I see, then I was right in my assumptions.

Then this means I will likely be "bitten by" docker/docker#6880 on all my other container builds, correct? 

For example if I wish to run php5-fpm, which I currently have the exact same issue with. Also solved with the same compromise.

**Comment by vorodev** [comment]
I managed to run nginx as www-data.
First, you need to comment out the hard-coded log paths in the compilation options. You can override options in config file, but compilation defaults are tested anyway.

Then, this should work

``` docker
EXPOSE 8080
USER www-data
ADD nginx-log.conf /etc/nginx.conf
ADD pub /usr/local/nginx/html
```

nginx-log.conf is the default upstream config file with a few changes

``` nginx
daemon off;
http {
    access_log syslog:server=SYSLOG_IP;
    error_log syslog:server=SYSLOG_IP;
}
server {
    listen       8080;
}
```

The drawback is that you need a separate syslog server, but it can be run in another container easily.

**Comment by AsavarTzeth** [comment]
Correct me if I am wrong here, since I am not a docker pro myself.

vordev's method is not a solution, because docker managing the logs is an essential function. For example, I could not be without "docker logs" during build debugging.

I also like to keep separate containers optional as much as possible. For example I will always have sqlite as an option, if supported. In fact I will support every choice of database supported and will likely make a pull request for this in the current official Wordpress build.

**Comment by vorodev** [comment]
I know it's not a solution. At most a workaround, but it works if running as non-root is a must.
I understand your logging needs, but for me it's the opposite, I have to aggregate several nginx and app server logs together.
I hope someone can find a solution for 6880. There are a few scenarios where I'd really like writing to fds as non-root.
I'm still working on a independent setup (no external log server). If I have any succes, I'll post it here.

**Comment by AsavarTzeth** [comment]
I believe there are already solutions out there that collects and manages
several logs via Docker. I have not tried any myself but they would replace
a syslog container in your use cases.

As for the root issue you are correct and kudos to you for those that need
it. I am sure it will be prove usefull to some.
Den 1 sep 2014 14:24 skrev "Voro" notifications@github.com:

**Comment by tianon** [comment]
Sorry for not updating here sooner: Nginx upstream is now providing and maintaining this image at [nginxinc/docker-nginx](https://github.com/nginxinc/docker-nginx).
