### ISSUE TITLE
Build with packages?

### ISSUE THREAD

**Issue by magnusp** [docker-library/nginx#5]
Is there a particular reason why the nginx is compiled from source instead of using the official packages ? Could it be --http-log-path and --error-log-path? I see the problem with additional modules (such as the recently added perl support) but this I believe should be up to the end user. The added benefits of using distribution packages are:
- Consistent directory layout with the distribution image.
- Avoids bloating the image with development packages and intermediate build directories.

Consider perhaps publishing two builds: one based off of the nginx package and one off of nginx-extras. This at least allows a choice of core and/or optional nginx modules.

Also, perhaps nitpicking, jessie is still in testing. Perhaps use debian:stable instead of debian:jessie?

**Comment by yosifkit** [comment]
We are currently building from source in order to attract upstream to maintain, but we are looking to make it easier to maintain so it could move to be built from the official packaging like [postgres](http://github.com/docker-library/postgres).

**Comment by tianon** [comment]
Interesting.  http://nginx.org/en/docs/install.html makes it sound like using the packages is acceptable and that building from source is not necessarily preferred.

@yosifkit, didn't you have some other page you were reading where upstream mentioned that they specifically prefer that users build from source and only use the packages as necessary/fallback?

**Comment by yosifkit** [comment]
I recall something similar, but it was redis you are thinking of that had the "only build from source".  I did not realize that they had packages; I only visited the download page and must have ignored the "pre-built" packages link at the bottom.

**Comment by yosifkit** [comment]
Fixed!

Nginx upstream will now be providing and maintaining the images [nginxinc/docker-nginx](https://github.com/nginxinc/docker-nginx).
