### ISSUE TITLE
nginx serves corrupted files when files edited in host mounted volume

### ISSUE THREAD

**Issue by stefanfoulis** [docker-library/nginx#8]
I'm not sure if this issues lies with docker itself, docker-osx or nginx.
noplay/docker-osx#68

**Comment by tianon** [comment]
This is probably related to this:
https://www.virtualbox.org/ticket/10660?cversion=0&cnum_hist=1

(ie, VBox guest additions don't support inotify)

**Comment by tianon** [comment]
It could also be https://github.com/docker-library/nginx/issues/6 - are you mounting a single file and then sending a `SIGHUP` to nginx, or are you mounting a directory?  Also, are we talking about the configuration files, or HTML files being served by nginx?

**Comment by stefanfoulis** [comment]
I'm mounting a whole directory of files to be served from `/usr/local/nginx/html`.

If the problem has to do with inotify it would mean that nginx or the sharing mechanism uses inotify to detect file length, but not for the content. And the weird thing is, that nginx will continue to serve an old version of the file even after destroying the container and re-creating it. Which points in the direction of problem with the mounting in Virtualbox not picking up on the changes (file length vs file content) correctly.

**Comment by tianon** [comment]
Sorry for not updating here sooner: Nginx upstream is now providing and maintaining this image at [nginxinc/docker-nginx](https://github.com/nginxinc/docker-nginx).
