### ISSUE TITLE
"WORKDIR /usr/local/nginx/html" assumes I have a /usr/local/nginx/html

### ISSUE THREAD

**Issue by stuartpb** [docker-library/nginx#9]
Trying to run this with my container's configuration got `finalize namespace chdir to /usr/local/nginx/html no such file or directory`

**Comment by stuartpb** [comment]
Actually, this was just when I was assuming I could import my conf with `-v /etc/nginx:/usr/local/nginx`. I see now that it needs to go somewhere else.

**Comment by yosifkit** [comment]
We have a possible solution to make it more user friendly (and how you expected it). 

See #10

**Comment by stuartpb** [comment]
Where I'd _really_ like to mount it is `/etc/nginx`, the same place as I place it in Arch and Ubuntu. I'm currently putting it under `/usr/local/nginx/etc` (since that was noted in the documentation somewhere) and explicitly naming the path.

**Comment by yosifkit** [comment]
Fixed to use `/etc/nginx/`.  (should be up in 4-5 hours)

Nginx upstream will now be providing and maintaining the images [nginxinc/docker-nginx](https://github.com/nginxinc/docker-nginx).
